### ISSUE TITLE
delete-unnused-aws-loggroups - document what constitutes "unused"

### ISSUE THREAD

**Issue by timrobinson33** [itmettkeDE/lambdas#15]
It would be really useful to document exactly what determines whether a log group is "unused"

I don't know rust but as far as I can tell from the source, it seems to only be looking for (a) lambda logs corresponding to lambda functions that don't exist, (b) codebuild logs corresponding to projects that don't exist. Other types of logs are left untouched.

**Comment by mettke** [comment]
Yes your statement is correct. At least for the moment. 

However you do have a point in writing something in the readme. I should be able to do this this weekend.

**Comment by mettke** [comment]
Updated documentation can be found here:
https://github.com/itmettkeDE/lambdas/tree/main/delete-unnused-aws-loggroups#delete-unnused-aws-loggroups
